services:
  otelcol-contrib:
    image: otel/opentelemetry-collector-contrib
    command: ["--config", "/etc/otelcol-contrib/config.yaml"]
    volumes:
      - ./config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"